name: deploy_dev
on:
  push:
    tags:        
      - '*'
env:
  FUNCTION_NAME: test-function
jobs:
  deploy:
    name: 'Deploy To Prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: deploy
      - name: Install Dependencies
        run: |
          npm install
      - name: Deploy To AWS Lambda
        run: |
          files=$(ls)
          for file in ${files}; do
            echo "file name: ${file}"
            extension="${file##*.}"
            if [ "${extension}" = "js" ] || [ "${extension}" = "ts" ]; then
              zip -r ../function.zip $file node_modules/ package.json package-lock.json
              function_name="${file%.*}"
              echo "deploying function #{function_name}"
              aws lambda update-function-code \
                --function-name ${function_name} \
                --zip-file fileb://../function.zip \
                --publish
            else
              echo "file extension is not in the list, skipping deployment..."
            fi
          done
