name: deploy_dev
on:
  push:
    tags:        
      - '*'
env:
  FUNCTION_NAME: test-function
jobs:
  deploy:
    name: 'Deploy To Dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: deploy
      - name: Install Dependencies
        run: |
          npm install
      - name: Package Functions
        run: |
          zip -r ../function.zip .
      - name: Deploy To AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${FUNCTION_NAME}-dev \
            --zip-file ../function.zip \
            --publish
